[workspace]
members = [
    "node",
    "runtime",
    "primitives/sm2",
    "pallets/template",
    "utils",
    "utils/subxt"
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"